### ISSUE TITLE
Issue with get_forecast

### ISSUE THREAD

**Issue by iMarcello** [crazycapivara/owmr#18]
[https://github.com/cran/owmr/issues/1#issue-534709583](https://github.com/cran/owmr/issues/1#issue-534709583)

**Comment by crazycapivara** [comment]
@iMarcello try installing fix:

```r
remotes::install_github("crazycapivara/owmr", ref = "fix/deprecated-warning-tidyr")
```

If everything is fine I will merge it to master and push a new version to CRAN.

**Comment by iMarcello** [comment]
> @iMarcello try installing fix:
> 
> ```r
> remotes::install_github("crazycapivara/owmr", ref = "fix/deprecated-warning-tidyr")
> ```
> 
> If everything is fine I will merge it to master and push a new version to CRAN.

Hi, thank you very much for the fast response!

The code run clean; however, the code below:
```
(owm_data7 <- find_city(lat = 12.17, lon = -83.04, cnt = 20, units = "metric") %>%
+   owmr_as_tibble() %>% .[, 1:23]) %>% names()
```
send the following error:
```
Error in UseMethod("unnest") : 
  no applicable method for 'unnest' applied to an object of class "NULL"
```
It is very strange because **almost the same piece of code below** ran clean:
```
(owm_data6 <- find_city(lat = 12.927994, lon = -85.911560, cnt = 50, units = "metric") %>%
  owmr_as_tibble() %>% .[, 1:23]) %>% names()
```
Regards, Marce

**Comment by crazycapivara** [comment]
Hm,

I tested your code, but cannot reproduce the error, for me both requests work.

`no applicable method for 'unnest' applied to an object of class "NULL"` suggests that the response was `NULL` or the response did not contain the `lists` object (`owm_data7$list`).

Could you check it again, maybe the server did not respond in that case.

**Comment by iMarcello** [comment]
Hi Stefan,
Run once again today without errors, It could be a non response from server side, as you mention.
Thanks again, Marce.
